baseurl = "https://gitboo.github.io/"
languageCode = "en-us"
title = "BooBlog - a minimal theme for Hugo"
theme = "mainroad"
#theme = "hugo-steam-theme"
disqusShortname = "spf13"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10
tag = "tags"
category = "categories"

[params]
	title = "Steam"
	subtitle = "a minimal theme for ~~Ghost~~ Hugo"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	CUstomJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Boo"
	bio = "programmer - blogger"
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = ""
	twitter = ""
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "gitboo"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
